repos:
  - repo: local
    hooks:
      - id: pycln
        name: pycln
        entry: poetry run pycln
        language: system
        args: [--config=pyproject.toml]
        types: [python]
        stages: [commit]

      - id: black
        name: black
        entry: poetry run black
        language: system
        minimum_pre_commit_version: 2.9.2
        types_or: [python, pyi]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        stages: [commit]
        exclude: ^(tests|benchmarks)/

      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        require_serial: true
        exclude: ^(tests|benchmarks)/
